### ISSUE TITLE
Mình đang xài flair để train phải không bạn?

### ISSUE THREAD

**Issue by yellow1912** [undertheseanlp/ner#2]
https://github.com/zalandoresearch/flair

Mình thấy hình như bạn đang xài flair phải không? Nếu mình muốn xài dataset của bạn để NER tiếng Việt có được không?

**Comment by rain1024** [comment]
> https://github.com/zalandoresearch/flair
> Mình thấy hình như bạn đang xài flair phải không?

Đúng rồi bạn

> Nếu mình muốn xài dataset của bạn để NER tiếng Việt có được không?
Bạn có thể dùng cho mục đích nghiên cứu và học tập nhé. Với mục đích thương mại bạn liên hệ với [VLSP](http://vlsp.org.vn/) để có xin quyền nhé.

**Comment by rain1024** [comment]
> Cảm ơn bạn, mình có lên site của VLSP để gửi contact mà bị lỗi:
> 
> ![image](https://user-images.githubusercontent.com/374134/51096485-59a32f00-17ef-11e9-954a-15317cc1729c.png)

Mình vào vẫn bình thường mà nhỉ

> Bạn có biết cách nào tốt nhất để liên hệ VLSP không?

Theo như mình được biết thì bạn có thể gửi mail vào địa chỉ vlsp.resources@gmail.com để liên hệ với VLSP nhé

**Comment by yellow1912** [comment]
Submit form moi bi loi ban oi, cam on ban da cho minh email.

**Comment by Crescentz** [comment]
Hello, I have the same problem, I want to get the data of VLSP and had tried email vlsp.resources@gmail.com and project manager,both get no reply.
