### ISSUE TITLE
the fourth column meaning of ner output

### ISSUE THREAD

**Issue by Hope-Rita** [undertheseanlp/ner#4]
I want to ask about where can the type and meaning of the fourth column of the output be found?

**Comment by rain1024** [comment]
@Hope-Rita I don't understand what you mean. The fourth column of what?

**Comment by Hope-Rita** [comment]
such as this 
>>> sentence = "Ông Putin ca ngợi những thành tựu vĩ đại của Liên Xô"
    >>> ner(sentence)
    [('Ông', 'Nc', 'B-NP', 'O'),
    ('Putin', 'Np', 'B-NP', 'B-PER'),
    ('ca ngợi', 'V', 'B-VP', 'O'),
    ('những', 'L', 'B-NP', 'O'),
    ('thành tựu', 'N', 'B-NP', 'O'),
    ('vĩ đại', 'A', 'B-AP', 'O'),
    ('của', 'E', 'B-PP', 'O'),
    ('Liên Xô', 'Np', 'B-NP', 'B-LOC')]
    """
 the meaning of O' 'B-PER' ……

**Comment by rain1024** [comment]
@Hope-Rita  you're correct.

**Comment by Hope-Rita** [comment]
Thank you!
