### ISSUE TITLE
Dữ liệu VLSP 2018

### ISSUE THREAD

**Issue by anhln** [undertheseanlp/ner#7]
Mình có thể xin dữ liệu VLSP 2018 về Named Entity Recognition được ko?

**Comment by rain1024** [comment]
@anhln underthesea không sở hữu và không có quyền phân phối dữ liệu VLSP. Bạn hãy email vào địa chỉ vlsp.resources@gmail.com để xin trực tiếp nhóm tác giả bạn nhé

**Comment by anhln** [comment]
Thanks bạn

Vào 13:05, T.6, 7 Th8, 2020 Vu Anh <notifications@github.com> đã viết:
